
### GET ALL ACTIVE COMMUNITY GALLERIES

GET http://localhost:5000/api/galleries/

### GET ALL GALLERIES FROM USER 

GET http://localhost:5000/api/galleries/68866309-361c-445b-a7d6-0093bbea0c14

### POST NEW GALLERY

POST http://localhost:5000/api/galleries
Content-Type: application/json
    
{
    "u_id": "ce7c566f-4a59-4474-84e8-5ffe8a5c3b6c",
    "g_name": "Venedig",
    "g_active": "true"
}

### UPDATE G_ACTIVE GALLERY

PATCH  http://localhost:5000/api/galleries
Content-Type: application/json

{
    "ids": [
        "19e7a1d1-10d5-40a5-b529-2bb74846736c", 
        "68866309-361c-445b-a7d6-0093bbea0c14",
    ],

    "set": "true"
}

### DELETE USER GALLERY

@var_g_id = 19e7a1d1-10d5-40a5-b529-2bb74846736c
@var_u_id = 68866309-361c-445b-a7d6-0093bbea0c14

DELETE http://localhost:5000/api/galleries/?g_id=1fab03df-ab43-4b04-9452-e3f780ff9862
